import type { Metadata } from "next";
import { Oswald, Inter } from "next/font/google"; // Import both fonts
import "./globals.css";
import Header from "./components/Header";

// Initialize Oswald
const oswald = Oswald({
  variable: "--font-oswald",
  subsets: ["latin"],
});

// Initialize Inter
const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "FitLog — Workout Library",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      // Inject both font variables into the className string
      className={`${oswald.variable} ${inter.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Header />

        <div>{children}</div>
      </body>
    </html>
  );
}
